name: Analysis

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
  schedule:
    - cron: "0 11 * * 0" # 3 AM PST = 12 PM UDT, runs sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-java:
    name: Backend Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    uses: ./.github/workflows/.tests.yml

  trivy:
    name: Repository Report
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          scan-type: "fs"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@a8d1ac45b9a34d11fe398d5503176af0d06b303e # v3
        with:
          sarif_file: "trivy-results.sarif"

  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: github/codeql-action/init@a8d1ac45b9a34d11fe398d5503176af0d06b303e # v3
        with:
          languages: javascript,java

      # Autobuild failed for Java, so building manually
      - name: Set up JDK 17 and Caching maven dependencies
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
          server-id: "github"

      # Java builds
      - name: Build Core
        working-directory: core
        run: mvn clean package install -DskipTests -Dtests.skip=true

      - name: Build Spring        
        working-directory: spring
        run: mvn clean package -DskipTests -Dtests.skip=true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@a8d1ac45b9a34d11fe398d5503176af0d06b303e # v3

  results:
    name: Analysis Results
    # needs: [codeql, tests-java, trivy] - uncomment when/if Trivy stops failing (upstream problem)
    needs: [codeql, tests-java]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Workflow completed successfully!"
