name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  vars:
    name: Variables
    runs-on: ubuntu-24.04
    outputs:
      semver: ${{ steps.semver.outputs.version }}
      tag: ${{ steps.semver.outputs.tag }}
    steps:
      # steps.semver.outputs.tag => needs.vars.outputs.semver
      - uses: actions/checkout@v5
        with:
          ref: refs/heads/${{ github.event.repository.default_branch }}
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765 # v6.0.0
        id: semver
        with:
          git-branch: refs/heads/${{ github.head_ref }}
          git-push: 'false'
          skip-commit: 'true'
          skip-on-empty: 'false'
          skip-version-file: 'true'

      - run: |
          echo "semver=${{ steps.semver.outputs.version }}"
          echo "tag=${{ steps.semver.outputs.tag }}"

  validate:
    name: Validate PR
    needs: [vars]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@d9b3d32fb3f03c4699c2dce83ddfff042cd31a1f # v1.0.0
    with:
      markdown_links: |
        Any successful releases will be available as the following dependencyes:
        ```
          <dependency>
            <groupId>ca.bc.gov.nrs-commons</groupId>
            <artifactId>forest-client-core</artifactId>
            <version>${{ needs.vars.outputs.semver }}.PR${{ github.event.number }}</version>
          </dependency>
          ```

          ```
          <dependency>
            <groupId>ca.bc.gov.nrs-commons</groupId>
            <artifactId>forest-client-spring</artifactId>
            <version>${{ needs.vars.outputs.semver }}.PR${{ github.event.number }}</version>
          </dependency>
          ```

          Once merged, the code will be promoted and handed off to the following workflow run.
          [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  changelog:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - name: Checkout branch
        uses: actions/checkout@v5
        with:
          ref: refs/heads/${{ github.head_ref }}

      - name: Conventional Changelog Update
        id: changelog
        continue-on-error: true
        uses: TriPSs/conventional-changelog-action@5f00b899ccbbcbc112bd6d715d5e76e7a9e4501d # v6
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          git-branch: refs/heads/${{ github.head_ref }}

      - name: Checkout pr
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Comment PR
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        if: steps.changelog.outputs.skipped == 'false'
        with:
          message: |
            # Current changelog

            ${{ steps.changelog.outputs.clean_changelog }}
          comment_tag: "# Current changelog"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  results:
    name: Validate Results
    needs: [changelog, validate]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Workflow completed successfully!"
