name: Reusable Unit Tests and Analysis

on:
  workflow_call:

jobs:
  vars:
    name: Variables
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.version }}
      tag: ${{ steps.semver.outputs.tag }}
    steps:
      # steps.semver.outputs.tag => needs.vars.outputs.semver
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ github.event.repository.default_branch }}
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v5.3.0
        id: semver
        with:
          git-branch: refs/heads/${{ github.head_ref }}
          git-push: 'false'
          skip-commit: 'true'
          skip-on-empty: 'false'
          skip-version-file: 'true'

      - run: |
          echo "semver=${{ steps.semver.outputs.version }}"
          echo "tag=${{ steps.semver.outputs.tag }}"

  trivy:
    name: Repository Report
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          scan-type: "fs"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-22.04
    needs: [vars]
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript,java

      # Autobuild failed for Java, so building manually
      - name: Set up JDK 17 and Caching maven dependencies
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
          server-id: "github"

      # Java builds
      - name: Build Core
        working-directory: core
        run: mvn clean package

      - name: Build Spring
        if: github.event_name != 'pull_request'
        uses: nick-fields/retry@v2        
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          retry_wait_seconds: 90
          command: |
            cd spring  
            mvn clean package -Dcore.version=${{ needs.vars.outputs.semver }}
      
      - name: Build Spring
        if: github.event_name == 'pull_request'
        working-directory: spring
        run: mvn clean package -Dcore.version=${{ needs.vars.outputs.semver }}.PR${{ github.event.number }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
